version: '3.2'

services:
  app:
    build: ./app
    container_name: app-flask
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    env_file:
      - .env_sample
    command: python3 core.py

  db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=game_db
    ports:
      - "5432:5432"
